version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          install-command: cd client && yarn install --frozen-lockfil
          start:  yarn run serve
          wait-on: 'http://localhost:3000'
