version: 2.1
jobs:
  build:
    docker:
      image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - "v1-dependencies-{{ checksum \"package.json\" }}"
            - v1-dependencies-
      - run: yarn install
      - run: cd client && yarn install
      - run: yarn start
      - save_cache:
          key: "v1-dependencies-{{ checksum \"package.json\" }}"
          paths:
            - node_modules
  test:
    docker:
      image: cypress/base:8
      environment:
        TERM: xterm
    steps:
      - run: cypress run
workflows:
    build-and-test:
      jobs:
        - build
        - test
