version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:latest
  cypress:
    docker:
      - image: cypress/base:8
jobs:
  build:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: yarn install
      - run: cd client && yarn install
      - run: yarn start
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    steps:
      - run: cypress run
workflows:
    build-and-test:
      jobs:
        - build
        - test
