version: 2.1
jobs:
  build:
    docker:
      image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: yarn install
      - run: cd client && yarn install
      - run: yarn start
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    docker:
      image: cypress/base:8
    steps:
      - run: cypress run
workflows:
    build-and-test:
      jobs:
        - build
        - test
