version: 2
jobs:
  build:
    working_directory: ~/qa_manager/client
    docker:
    - image: circleci/node:latest

    steps:
    - run:
        name: Install
  cypress/run:
    docker:
    - image: cypress/base:10
    parallelism: 1
    steps:
    - checkout:
        path: ~/qa_manager
    - run:
        name: Install
        command: yarn install --frozen-lockfile
    - run:
        name: Verify Cypress
        command: yarn cypress verify
    - run:
        name: Run Tests
        no_output_timeout: 10m
        command: yarn test-ci
workflows:
  build:
    jobs:
    - cypress/run
  version: 2
