version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.0
workflows:
  build:
    jobs:
    - cypress/run:
       yarn: true
       start: yarn start:ci
       wait-on: 'http-get://127.0.0.1:3000'
       cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "client/package.json"
            }}
       working_directory: client
       command: yarn ci:cypress:run
